version: "3"
services:
  app:
    build: .
    container_name: quiz_internship
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db-postgres
      - db-redis

  db-postgres:
    image: postgres
    container_name: db-postgres
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  db-redis:
    image: redis
    container_name: db-redis
    env_file:
      - .env
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  postgres-db:
  redis-data:
