version: "3"
services:
  app:
    build: .
    container_name: quiz_internship
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
