"""edit user

Revision ID: 8b1a751e6f3d
Revises: dfccc4d0c87b
Create Date: 2022-10-21 17:28:06.267965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1a751e6f3d'
down_revision = 'dfccc4d0c87b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_company_id_fkey', 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key('requests_company_id_fkey', 'requests', 'users', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
