"""edit request

Revision ID: d18994a410ce
Revises: 39dc2571578e
Create Date: 2022-10-21 15:55:56.078365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType


USER = 'user'
COMPANY = 'company'

REQUEST_SENDER = [
    (USER, 'user'),
    (COMPANY, 'company')
]

# revision identifiers, used by Alembic.
revision = 'd18994a410ce'
down_revision = '39dc2571578e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('sender', ChoiceType(REQUEST_SENDER), server_default='user', nullable=False))
    op.drop_column('requests', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('requests', 'sender')
    # ### end Alembic commands ###
