"""edit request2

Revision ID: dfccc4d0c87b
Revises: d18994a410ce
Create Date: 2022-10-21 16:10:24.722618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType

# revision identifiers, used by Alembic.
revision = 'dfccc4d0c87b'
down_revision = 'd18994a410ce'
branch_labels = None
depends_on = None

CONFIRMED = 'confirmed'
REJECTED = 'rejected'
CREATED = 'created'

REQUEST_STATUS = [
    (CONFIRMED, 'confirmed'),
    (REJECTED, 'canceled'),
    (CREATED, 'completed')
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', ChoiceType(REQUEST_STATUS), server_default='created', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status')
    # ### end Alembic commands ###
