"""correct field choice_answers

Revision ID: f1e8eced80ab
Revises: fe1b78c2f8c2
Create Date: 2022-10-25 15:11:45.139006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1e8eced80ab'
down_revision = 'fe1b78c2f8c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('choice_answers', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('questions', 'choice_answers')
    # ### end Alembic commands ###
