"""add company_id in quiz

Revision ID: fe1b78c2f8c2
Revises: 6deeeff798ab
Create Date: 2022-10-25 12:20:24.919733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1b78c2f8c2'
down_revision = '6deeeff798ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quiz', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'company_id')
    # ### end Alembic commands ###
